services:
  real_rl:
    image: real_rl_${USER}:latest
    container_name: rl_${USER}
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TERM=xterm
    volumes:
      - /tmp/.X11-unix:/tml/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - ./:/root/workspace/
    tty: true
    stdin_open: true
    network_mode: "host"
    privileged: true
    ulimits:
      rtprio: 70
      rttime: -1
      memlock: 8428281856
    devices:
      - "/dev:/dev"
    command: /bin/bash
